name: Compilar para Game Stick
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: pcsxredux/nugget:latest
    steps:
      - uses: actions/checkout@v4
      - name: Compilar
        run: |
          echo 'TARGET = baldi_psx' > Makefile
          echo 'SRCS = main.c' >> Makefile
          echo 'LIBS = -lgpu -lgte -letc -lapi -lc' >> Makefile
          echo 'include /nugget/common.mk' >> Makefile
          make
          echo 'FILE "BaldiPSX.bin" BINARY' > BaldiPSX.cue
          echo '  TRACK 01 MODE1/2352' >> BaldiPSX.cue
          echo '    INDEX 01 00:00:00' >> BaldiPSX.cue
          cp baldi_psx.exe BaldiPSX.bin
      - name: Enviar Jogo
        uses: actions/upload-artifact@v4
        with:
          name: jogo-baldi-gamestick
          path: |
            BaldiPSX.bin
            BaldiPSX.cue
            
            
